openapi: 3.0.0
info:
  title: Go Moment API Reference
  description: |
    The Go Moment API is organized around [REST](http://en.wikipedia.org/wiki/Representational_State_Transfer)

    ### Terms of Service
    By accessing or using our APIs, you are agreeing to our [Terms of service](https://ivy.gomoment.com/api/v1/docs/terms)

    # Authentication

    Go Moment authentication uses an API_KEY to allow for secure authorization.

    In the Authorization header, the parameter value must be "Token token=API_KEY" (no spaces)

    <SecurityDefinitions />
  version: "1.0.0"

  x-logo:
      url: https://www.gomoment.com/wp-content/uploads/2020/11/gm_logo.png
      altText: Ivy Logo

servers:
  - url: https://ivy.gomoment.com/api/v1
    description: Production server
  - url: https://sandbox.gomoment.com/api/v1
    description: Sandbox server

tags:
  - name: visits
    description: Create or update guest visits
    x-displayName: Visits
  - name: smart_response
    description: Return Smart Response based on incoming message
    x-displayName: Smart Response
  - name: visit_model
    x-displayName: Visit Object
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/VisitObject" />

x-tagGroups:
  - name: Guest Routes
    tags:
      - visits
  - name: Messaging Routes
    tags:
      - smart_response
  - name: Models
    tags:
      - visit_model


paths:

# Visits Endpoint

  /visits:
    post:
      tags:
        - visits
      summary: Visits
      security:
        - ApiKeyAuth: []
      x-codeSamples:
        - lang: 'cURL'
          source: |
            curl -X POST \
            https://ivy.gomoment.com/api/v1/visits \
            -H 'Authorization: Token token="YOUR_API_KEY"' \
            -H 'Content-Type: application/json' \
            -d '{
              "visits": [
              {
                "guest_name_first": "First",
                "guest_name_last": "Last",
                "guest_mobile_number": "+18558881234",
                "guest_email": "first.last@gomoment.com",
                "room": "1234",
                "check_in_date": "2020-10-10",
                "check_in_time": "15:00",
                "check_out_date": "2020-10-15",
                "check_out_time": "12:00",
                "opt_in_date": "2020-10-10",
                "opt_in_time": "15:00",
                "status": "CI",
                "custom_event": "ready",
                "tags": {
                  "add": [
                    "gold"
                  ],
                  "remove": [
                    "silver", "diamond"
                  ]
                },
                "extra": {
                  "customTag": "value"
                }
              }
              ]
            }'
      requestBody:
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/VisitsArray'
          required: true
      responses:
        '200':
          description: |
            ## Request Received
            Request was successfully received and there are no
            issues with the RequestBody
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/VisitSuccessResponse'
              examples:
                SuccessResponse:
                  value:
                    received_records: 2
                    valid_records: 2
                    errors: []
                SuccessErrorResponse:
                  value:
                    received_records: 2
                    valid_records: 1
                    errors: ["+123 is an invalid number"]
        '400':
          description: |
            ## Request Body Error
            Error in request body. Check to make sure your request
            conforms with the provided schemas.
        '401':
          description: |
            ## Unauthorized Access
            Check your authorization to make sure that you have string =
            "Token token=API_KEY"
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/UnauthorizedError'
              example:
                code: 401
                message: 'HTTP Token: Access Denied'
        '422':
          description: |
            ## Missing Parameter
            Check to make sure all required fields are included
            in your API call.
            Error will provide which field is missing - {missing_field}.
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/GeneralError'
              example:
                code: 422
                message: 'Missing parameter {missing_field}'

# Smart Response Endpoint
  /replies:
    post:
      tags:
        - smart_response
      summary: Smart Response
      security:
        - ApiKeyAuth: []
      x-codeSamples:
        - lang: 'cURL'
          source: |
            curl -X POST \
            'https://ivy.gomoment.com/api/v1/replies?content=wifi&content_type=sms&content_type=whatsapp' \
            -H 'Authorization: Token token=YOUR_API_KEY'

      parameters:
        - in: query
          name: content
          description: |
            Incoming message content
          schema:
            type: string
          example: "wifi"
          required: true
        - in: query
          name: content_type
          schema:
            $ref: '#/components/schemas/ContentType'
          examples:
            single:
              value:
                - sms
            multi:
              value:
                - sms
                - whatsapp
      responses:
        '200':
          description: |
            ## Request Received
            Request was successfully received and there are no
            issues with the provided parameters
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/SRSuccessResponse'
              example:
                smart_response_name: Wifi Info
                smart_response_content: The wifi password is 1234
                message: The wifi password is 1234
                ai_intent:
                    intent_name: Wifi Info
                    confidence_level: 95.20
                    sentiment_score: 0.0

        '400':
          description: |
            ## Request Parameter Error
            Error in request parameters. Check to make sure your request
            conforms with the provided schemas.
        '401':
          description: |
            ## Unauthorized Access
            Check your authorization to make sure that you have string =
            "Token token = API_KEY"
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/UnauthorizedError'
              example:
                code: 401
                message: 'HTTP Token: Access Denied'
        '422':
          description: |
            ## Content Error
            Either content is invalid or a response cannot be found.
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ContentError'
              examples:
                invalid:
                  value:
                    message: Content types invalid_here not allowed
                no_response:
                  value:
                    message: Can't find a response for that


# Components
components:
  schemas:

    # Success Responses
    VisitSuccessResponse:
      type: object
      properties:
        received_records:
          type: integer
          description: Number of VisitObjects received
        valid_records:
          type: integer
          description: Number of VisitObjects that are valid
        errors:
          type: array
          items:
            type: string
            description: |
              Describes errors that may be received.
              The most common error is that an invalid number was entered

    SRSuccessResponse:
      type: object
      description: |
        ## Smart Response Object
        Provides content and AI intent detected
      properties:
        smart_response_name:
          type: string
          description: Maps to "Topic" in Ivy Setup
        smart_response_content:
          type: string
          description: Maps to "Ivy AI Smart Responses" in Ivy Setup
        message:
          type: string
          description: Maps to "Ivy AI Smart Responses" in Ivy Setup
        ai_intent:
          type: object
          properties:
            intent_name:
              type: string
              description: Intent recognized by AI
            confidence_level:
              type: number
              format: float
              description: Confidence level of intent recognition
            sentiment_score:
              type: number
              format: float
              description: "Guest sentiment ranging from -1.0 to +1.0"

    # Error Responses
    GeneralError:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
    UnauthorizedError:
      description: API key is missing or invalid
    ContentError:
      type: object
      properties:
        message:
          type: string

    # Input Schemas
    VisitsArray:
      type: object
      properties:
        visits:
          description: The visits array can contain one or more visits objects
          type: array
          items:
            $ref: '#/components/schemas/VisitObject'
    VisitObject:
      type: object
      required:
        - guest_name_first
        - guest_name_last
        - guest_mobile_number
        - check_in_date
        - status
      properties:
        guest_name_first:
          type: string
          example: First
        guest_name_last:
          type: string
          example: Last
        guest_mobile_number:
          type: string
          description: |
            Guest mobile number.
            This is required in order for Ivy to talk to your guests.
          example: '+18558881234'
        guest_email:
          type: string
          example: 'first.last@gomoment.com'
        room:
          type: string
          example: '1400'
        check_in_date:
          type: string
          description: |
            (Default) YYYY-MM-DD.
            Please speak to your customer success manager to revise formatting.
          example: '2020-10-10'
        check_in_time:
          description: |
            (Default) HH:MM.
            Please speak to your customer success manager to revise formatting.
          example: '15:00'
        check_out_date:
          type: string
          description: |
            (Default) YYYY-MM-DD.
            Please speak to your customer success manager to revise formatting.
          example: '2020-10-15'
        check_out_time:
          type: string
          description: |
            (Default) HH:MM.
            Please speak to your customer success manager to revise formatting.
          example: '12:00'
        opt_in_date:
          type: string
          description: |
            Date guest opted-in to marketing campaign.
            (Default) YYYY-MM-DD.
            Please speak to your customer success manager to revise formatting.
          example: '2020-10-10'
        opt_in_time:
          type: string
          description: |
            Time guest opted-in to marketing campaign.
            (Default) HH:MM.
            Please speak to your customer success manager to revise formatting.
          example: '15:00'
        status:
          type: string
          description: |
            Pre = Pre-Arrival (if enabled),
            CI = Check In,
            CO = Check Out,
            CL = Cancelled or Invalid.
            Please speak to your customer success manager if you would like to re-map these values.
          enum:
            - Pre
            - CI
            - CO
            - CL
          example: CI
        custom_event:
          type: string
          description: |
            ### Custom Events
            These events have custom keys that recognize a descrete value.
            Custom events are used to trigger automated campaigns once the appropriate
            value has been received.
            Please speak with your customer success manager to enable.
          example: ready
        tags:
          type: object
          $ref: '#/components/schemas/VisitTagItem'
        extra:
          type: object
          $ref: '#/components/schemas/CustomTags'

    VisitTagItem:
      type: object
      description: |
        Add or remove persistent guest tags.
        "Add" will include persistent tags to the guest until removed.
        "Remove" will remove the specified persistent tags associated with that guest, if they exist.
        We recommend that you use the "extra" payload instead.
      properties:
        add:
          type: array
          items:
            type: string
        remove:
          type: array
          items:
            type: string
      example:
        add:
          - gold
        remove:
          - silver
          - diamond
    CustomTags:
      type: object
      description: |
        Allows any key, value pair to be ingested.
        "CustomTag" can be any string that is mapped to a value that
        will be tagged to the guest.
        CustomTags can be either visit-only or persistent tags.
        Please speak with a customer sucess manager to enable.
      properties:
        CustomTag:
          type: string
          example: value
    ContentType:
      type: array
      description: |
        ### Content Types
        (Optional) Multi-value incoming message type.
        The most common is SMS.
      items:
        type: string
        enum:
          - webchat
          - sms
          - email
          - whatsapp



  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
      description: |
        API key provided by Go Moment.
        This can be found at Ivy Setup Wizard > Integrations > PMS Integration
